In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:

data1 = pd.read_csv("data/JC-202102-citibike-tripdata.csv", error_bad_lines=False)
data2 = pd.read_csv("data/JC-202103-citibike-tripdata.csv", error_bad_lines=False)
data3= pd.read_csv("data/JC-202104-citibike-tripdata.csv", error_bad_lines=False)
data4= pd.read_csv("data/JC-202105-citibike-tripdata.csv", error_bad_lines=False)
data5= pd.read_csv("data/JC-202106-citibike-tripdata.csv", error_bad_lines=False)
data6= pd.read_csv("data/JC-202107-citibike-tripdata.csv", error_bad_lines=False)
data7= pd.read_csv("data/JC-202108-citibike-tripdata.csv", error_bad_lines=False) 
data8= pd.read_csv("data/JC-202109-citibike-tripdata.csv", error_bad_lines=False) 
data9= pd.read_csv("data/JC-202110-citibike-tripdata.csv", error_bad_lines=False)

In [3]:
data1["month"]="February"

In [4]:
data2["month"]="March"

In [5]:
data3["month"]="April"

In [6]:
data4["month"]="May"

In [7]:
data5["month"]="June"

In [8]:
data6["month"]="July"

In [9]:
data7["month"]="August"

In [10]:
data8["month"]="September"

In [11]:
data9["month"]="October"

In [12]:
data1[["started_at", "ended_at"]]= data1[["started_at", "ended_at"]].apply(pd.to_datetime)

In [13]:
data3.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
month                  object
dtype: object

In [14]:
data3.columns.to_list()

['ride_id',
 'rideable_type',
 'started_at',
 'ended_at',
 'start_station_name',
 'start_station_id',
 'end_station_name',
 'end_station_id',
 'start_lat',
 'start_lng',
 'end_lat',
 'end_lng',
 'member_casual',
 'month']

In [15]:
citi_frames = [ data1, data2, data3, data4, data5, data6, data7, data8, data9]
citi_result = pd.concat(citi_frames)
citi_result

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,month
0,121DD7DD23CB1335,docked_bike,2021-02-03 23:11:28,2021-02-03 23:18:28,Hoboken Ave at Monmouth St,JC105,Christ Hospital,JC034,40.735208,-74.046964,40.734786,-74.050444,member,February
1,FD73FB85F008349D,docked_bike,2021-02-27 16:34:05,2021-02-27 16:56:40,Newport Pkwy,JC008,Marin Light Rail,JC013,40.728744,-74.032108,40.714584,-74.042817,member,February
2,39F9E6663CB5FDF6,docked_bike,2021-02-26 23:16:04,2021-02-26 23:22:25,Journal Square,JC103,Baldwin at Montgomery,JC020,40.733670,-74.062500,40.723659,-74.064194,member,February
3,A64745CB0792EC6F,docked_bike,2021-02-24 16:51:50,2021-02-24 17:16:09,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,casual,February
4,75CC76EB9543764A,docked_bike,2021-02-24 20:44:16,2021-02-24 20:44:46,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,member,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88757,2B1145DCE1C12234,classic_bike,2021-10-22 21:33:14,2021-10-22 21:56:13,Clinton St & 7 St,HB303,City Hall - Washington St & 1 St,HB105,40.745420,-74.033320,40.737360,-74.030970,casual,October
88758,9332D910D93C0961,classic_bike,2021-10-16 14:30:26,2021-10-16 14:35:43,Clinton St & 7 St,HB303,City Hall - Washington St & 1 St,HB105,40.745420,-74.033320,40.737360,-74.030970,casual,October
88759,9BD55309848AD745,classic_bike,2021-10-17 02:11:58,2021-10-17 02:18:26,Clinton St & 7 St,HB303,Grand St & 14 St,HB506,40.745420,-74.033320,40.754090,-74.031600,casual,October
88760,263F1EE58709CB6D,classic_bike,2021-10-07 20:38:47,2021-10-07 20:44:49,Clinton St & 7 St,HB303,Grand St & 14 St,HB506,40.745420,-74.033320,40.754090,-74.031600,casual,October
88761,2D38261C42BE80F3,classic_bike,2021-10-23 23:48:08,2021-10-23 23:55:02,Clinton St & 7 St,HB303,Grand St & 14 St,HB506,40.745420,-74.033320,40.754090,-74.031600,casual,October

In [16]:
concatenated_df = citi_result.rename(columns={
   
 "ride_id": "Ride ID",
 "rideable_type": "Ridable Type",
 "started_at": "Started At",
 "ended_at": "Ended At",
 "start_station_name": "Start Station Name",
 "start_station_id": "Start Station ID",
 "end_station_name": "End Station Name",
 "end_station_id":"End Station ID",
 "start_lat":"Start Latitude",
 "start_lng":"Start Longtitude",
 "end_lat":"End Latitude",
 "end_lng":"End Longitude",
 "member_casual":"Member Casual",
 "month": "Month"
      
})

concatenated_df

,Ride ID,Ridable Type,Started At,Ended At,Start Station Name,Start Station ID,End Station Name,End Station ID,Start Latitude,Start Longtitude,End Latitude,End Longitude,Member Casual,Month
0,121DD7DD23CB1335,docked_bike,2021-02-03 23:11:28,2021-02-03 23:18:28,Hoboken Ave at Monmouth St,JC105,Christ Hospital,JC034,40.735208,-74.046964,40.734786,-74.050444,member,February
1,FD73FB85F008349D,docked_bike,2021-02-27 16:34:05,2021-02-27 16:56:40,Newport Pkwy,JC008,Marin Light Rail,JC013,40.728744,-74.032108,40.714584,-74.042817,member,February
2,39F9E6663CB5FDF6,docked_bike,2021-02-26 23:16:04,2021-02-26 23:22:25,Journal Square,JC103,Baldwin at Montgomery,JC020,40.733670,-74.062500,40.723659,-74.064194,member,February
3,A64745CB0792EC6F,docked_bike,2021-02-24 16:51:50,2021-02-24 17:16:09,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,casual,February
4,75CC76EB9543764A,docked_bike,2021-02-24 20:44:16,2021-02-24 20:44:46,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,member,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88757,2B1145DCE1C12234,classic_bike,2021-10-22 21:33:14,2021-10-22 21:56:13,Clinton St & 7 St,HB303,City Hall - Washington St & 1 St,HB105,40.745420,-74.033320,40.737360,-74.030970,casual,October
88758,9332D910D93C0961,classic_bike,2021-10-16 14:30:26,2021-10-16 14:35:43,Clinton St & 7 St,HB303,City Hall - Washington St & 1 St,HB105,40.745420,-74.033320,40.737360,-74.030970,casual,October
88759,9BD55309848AD745,classic_bike,2021-10-17 02:11:58,2021-10-17 02:18:26,Clinton St & 7 St,HB303,Grand St & 14 St,HB506,40.745420,-74.033320,40.754090,-74.031600,casual,October
88760,263F1EE58709CB6D,classic_bike,2021-10-07 20:38:47,2021-10-07 20:44:49,Clinton St & 7 St,HB303,Grand St & 14 St,HB506,40.745420,-74.033320,40.754090,-74.031600,casual,October
88761,2D38261C42BE80F3,classic_bike,2021-10-23 23:48:08,2021-10-23 23:55:02,Clinton St & 7 St,HB303,Grand St & 14 St,HB506,40.745420,-74.033320,40.754090,-74.031600,casual,October

In [17]:
concatenated_df.dtypes

Ride ID                object
Ridable Type           object
Started At             object
Ended At               object
Start Station Name     object
Start Station ID       object
End Station Name       object
End Station ID         object
Start Latitude        float64
Start Longtitude      float64
End Latitude          float64
End Longitude         float64
Member Casual          object
Month                  object
dtype: object

In [20]:
concatenated_df.to_csv('Citi_Total_data.csv')